### ISSUE TITLE
Problem using the Ebsi driver

### ISSUE THREAD

**Issue by zennur** [decentralized-identity/universal-registrar#38]
When I try using the ebsi driver, both from the frontend and Docker image, I get error, possibly from the token. 
How am I supposed to use it? And which token should I use?

**Comment by azuzi** [comment]
@zennur please follow the following [link](https://app.preprod.ebsi.eu/users-onboarding/) and use either reCaptcha or EU login and use the resulting session token within the "secret" object as follows.
~~~
"secret":{"token:"............"} 
~~~

**Comment by azuzi** [comment]
This should help to resolve the issue so I'm closing the issue.
If the solution doesn't help feel free to re-open the issue.

**Comment by zennur** [comment]
Thank you, that solved the problem. 
I actually have a follow-up question.
Is there any documentation on what kind of methods we have and how can we use it?

**Comment by peacekeeper** [comment]
Hello @zennur you can see a list of supported methods in the README (https://github.com/decentralized-identity/universal-registrar#drivers) and also in the frontend (https://uniregistrar.io/).

Regarding how to use it, the "options" and "secret" input fields vary a bit depending on the DID method. Some of our drivers have method-specific documentation (e.g. see did:btcr https://github.com/decentralized-identity/uni-registrar-driver-did-btcr/), but others don't have all the info. Sorry about that, we will try to improve documentation on how exactly to use the methods. Also if you're a DIF member, feel free to ask in the [#wg-id](https://app.slack.com/client/T4VKPCU00/C4WED8JSH) Slack channel for support!
