### ISSUE TITLE
Final state-setters should remove existing interim states

### ISSUE THREAD

**Issue by cihanss** [decentralized-identity/universal-registrar#50]
When a [State](https://github.com/decentralized-identity/universal-registrar/blob/c44e8b38903a1867037119cf8e9856b16cb869e9/uni-registrar-core/src/main/java/uniregistrar/state/State.java) is set to [finished](https://github.com/decentralized-identity/universal-registrar/blob/c44e8b38903a1867037119cf8e9856b16cb869e9/uni-registrar-core/src/main/java/uniregistrar/state/SetStateFinished.java#L29)/[failed](https://github.com/decentralized-identity/universal-registrar/blob/c44e8b38903a1867037119cf8e9856b16cb869e9/uni-registrar-core/src/main/java/uniregistrar/state/SetStateFailed.java#L26), previous states of wait/action should be removed. Removing the interim states can be done manually, but it takes away from the utility of the state setters.

**Comment by peacekeeper** [comment]
I agree, maybe you can do a PR for this?
