### ISSUE TITLE
Get  a problem while running "docker-compose -f docker-compose.yml pull"

### ISSUE THREAD

**Issue by anaczeng** [decentralized-identity/universal-registrar#61]
I get a problem while running "docker-compose -f docker-compose.yml pull". It seems that I need some authentication.
The service "https://registry-1.docker.io/v2/" returns a message that :
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

![image](https://user-images.githubusercontent.com/30198041/178932322-2fbeefc5-7b26-44b2-ae98-931abb3f4f41.png)

Where did I go wrong? Thx!

**Comment by BernhardFuchs** [comment]
Just tried the `pull` and everything worked for me but I couldn't verify if it was downloading from https://registry-1.docker.io/v2/ or https://docker.io/v2/ (which would have been my guess)  

There are two possible issues here which come to my mind:
1. There is a misconfiguration in your docker environment and you are pulling from a protected subdomain (registry-1)
2. You need to log in to docker.io. Pls see official docker docs on how to do that https://docs.docker.com/engine/reference/commandline/login/
