### ISSUE TITLE
Cannot create DID using SOV method

### ISSUE THREAD

**Issue by jessecarter111** [decentralized-identity/universal-registrar#70]
Just downloaded the repo and ran docker-compose as instructed.

I am unable to perform a create operation using the sov method, as each attempt results in this error:

Created failed state: {"jobId":null,"didState":{"reason":"Driver: Create problem: Cannot open Indy connections: No 'walletName' for network: eesdi","state":"failed","error":"internalError"},"didRegistrationMetadata":{},"didDocumentMetadata":{}}

**Comment by peacekeeper** [comment]
Hello, looks like the configuration was a bit outdated. Should be fixed in https://github.com/decentralized-identity/universal-registrar/commit/535dd160cf244c1dd0664ac11982dae8ce0df546, can you pull the latest commits and try again?

**Comment by jessecarter111** [comment]
Latest commit has resolved the issue. Thank you!
